Repository Shredrox/UniVerse, pull requests merged in 2023-12, with the labels that each got.

#45 Create frontend Friends system
  UniVerseUI/universe-ui/package-lock.json
  UniVerseUI/universe-ui/package.json
  UniVerseUI/universe-ui/src/api/usersApi.js
  UniVerseUI/universe-ui/src/assets/images/background-profile.jpg
  UniVerseUI/universe-ui/src/components/SocialPanel.jsx
  UniVerseUI/universe-ui/src/components/UserPanel.jsx
  UniVerseUI/universe-ui/src/layouts/MainLayout.jsx
  UniVerseUI/universe-ui/src/pages/Profile.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#48 Create Jobs page
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/api/jobsApi.js
  UniVerseUI/universe-ui/src/components/JobFilter.jsx
  UniVerseUI/universe-ui/src/components/JobOffer.jsx
  UniVerseUI/universe-ui/src/pages/JobDetails.jsx
  UniVerseUI/universe-ui/src/pages/Jobs.jsx
  UniVerseUI/universe-ui/src/pages/NewsDetails.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#49 Create Events page
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/api/eventsApi.js
  UniVerseUI/universe-ui/src/components/Event.jsx
  UniVerseUI/universe-ui/src/components/TrendingEvent.jsx
  UniVerseUI/universe-ui/src/pages/Events.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#51 Create application.yml file.
  UniVerseAPI/universe/src/main/resources/application.properties
Labels: enhancement, back end, database

#61 Create DTOs.
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/CommentDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/FollowDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/LikeDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/PostDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/RolesDTO.java
Labels: enhancement, back end

#63 Create Notification system
  UniVerseUI/universe-ui/index.html
  UniVerseUI/universe-ui/package-lock.json
  UniVerseUI/universe-ui/package.json
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/Comment.jsx
  UniVerseUI/universe-ui/src/components/CommentSection.jsx
  UniVerseUI/universe-ui/src/components/Post.jsx
  UniVerseUI/universe-ui/src/components/Sidebar.jsx
  UniVerseUI/universe-ui/src/components/SocialPanel.jsx
  UniVerseUI/universe-ui/src/contexts/NotificationContext.jsx
  UniVerseUI/universe-ui/src/hooks/useNotification.js
  UniVerseUI/universe-ui/src/main.jsx
  UniVerseUI/universe-ui/src/pages/Settings.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#66 Create Chat system
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/api/chatsApi.js
  UniVerseUI/universe-ui/src/api/eventsApi.js
  UniVerseUI/universe-ui/src/api/jobsApi.js
  UniVerseUI/universe-ui/src/api/newsApi.js
  UniVerseUI/universe-ui/src/api/usersApi.js
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/ChatCard.jsx
  UniVerseUI/universe-ui/src/components/Comment.jsx
  UniVerseUI/universe-ui/src/components/CommentSection.jsx
  UniVerseUI/universe-ui/src/components/Post.jsx
  UniVerseUI/universe-ui/src/components/Sidebar.jsx
  UniVerseUI/universe-ui/src/components/SocialPanel.jsx
  UniVerseUI/universe-ui/src/contexts/NotificationContext.jsx
  UniVerseUI/universe-ui/src/contexts/SocketContext.jsx
  UniVerseUI/universe-ui/src/hooks/useNotification.js
  UniVerseUI/universe-ui/src/hooks/useSocket.js
  UniVerseUI/universe-ui/src/layouts/ChatsLayout.jsx
  UniVerseUI/universe-ui/src/main.jsx
  UniVerseUI/universe-ui/src/pages/Chat.jsx
  UniVerseUI/universe-ui/src/pages/Chats.jsx
  UniVerseUI/universe-ui/src/pages/Settings.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#67 Comment Controller created
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/AuthController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/CommentController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/CommentRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/CommentService.java
Labels: enhancement, back end

#69 52 enhance user registration security
  UniVerseAPI/Map/.idea/description.html
  UniVerseAPI/Map/out/production/Map/com/company/AutoClosableResource.class
  UniVerseAPI/Map/out/production/Map/com/company/BadNumberException.class
  UniVerseAPI/Map/out/production/Map/com/company/Crooissant.class
  UniVerseAPI/Map/out/production/Map/com/company/Exam.class
  UniVerseAPI/Map/out/production/Map/com/company/Main.class
  UniVerseAPI/Map/src/com/company/AutoClosableResource.java
  UniVerseAPI/Map/src/com/company/BadNumberException.java
  UniVerseAPI/Map/src/com/company/Crooissant.java
  UniVerseAPI/Map/src/com/company/Main.java
  UniVerseAPI/universe/pom.xml
  UniVerseAPI/universe/src/main/java/com/unidev/universe/UniverseApplication.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/JwtUtil.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/Roles.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/SecurityConfig.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/UserDetailsServiceImpl.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/config/PasswordEncoder.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/AuthController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/RegistrationController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/UserDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Roles.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/User.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/UserRole.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/RolesRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/UserRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/requests/LoginRequest.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/requests/RegisterRequest.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/requests/RegistrationRequest.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserFollowerResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserFollowingResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserJwtResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/RegistrationService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/UserService.java
  UniVerseAPI/universe/src/main/resources/application.yml
Labels: enhancement, back end, database

#73 Post Controller created
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/CommentController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/PostController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/PostRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/CommentService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/PostService.java
Labels: enhancement, back end

#75 Add frontend error handling
  UniVerseUI/universe-ui/package-lock.json
  UniVerseUI/universe-ui/package.json
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/assets/images/background-not-found-page.png
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/Comment.jsx
  UniVerseUI/universe-ui/src/components/CommentSection.jsx
  UniVerseUI/universe-ui/src/components/CreatePostForm.jsx
  UniVerseUI/universe-ui/src/components/Feed.jsx
  UniVerseUI/universe-ui/src/components/Post.jsx
  UniVerseUI/universe-ui/src/components/SocialPanel.jsx
  UniVerseUI/universe-ui/src/components/fallbacks/ErrorFallback.jsx
  UniVerseUI/universe-ui/src/components/fallbacks/Loading.jsx
  UniVerseUI/universe-ui/src/layouts/ChatsLayout.jsx
  UniVerseUI/universe-ui/src/main.jsx
  UniVerseUI/universe-ui/src/pages/Chat.jsx
  UniVerseUI/universe-ui/src/pages/Chats.jsx
  UniVerseUI/universe-ui/src/pages/ErrorPage.jsx
  UniVerseUI/universe-ui/src/pages/Events.jsx
  UniVerseUI/universe-ui/src/pages/JobDetails.jsx
  UniVerseUI/universe-ui/src/pages/Jobs.jsx
  UniVerseUI/universe-ui/src/pages/News.jsx
  UniVerseUI/universe-ui/src/pages/NewsDetails.jsx
  UniVerseUI/universe-ui/src/pages/NotFound.jsx
  UniVerseUI/universe-ui/src/pages/Profile.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#78 Create Notification controller and set up WebSocket config
  UniVerseAPI/universe/pom.xml
  UniVerseAPI/universe/src/main/java/com/unidev/universe/config/WebSocketConfig.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/NotificationController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Notification.java
Labels: enhancement, back end

#74 Created Event Controller
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/EventController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/EventRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/EventService.java
Labels: enhancement, back end

#79 Create Like Controller and refactoring other classes
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/UserDetailsServiceImpl.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/LikeController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/UserController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/UserDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/CommentRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/LikeRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/LikeService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/UserService.java
Labels: enhancement, back end

#81 Created News Controller
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/NewsController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/News.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/NewsRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/EventService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/NewsService.java
Labels: enhancement, back end

#82 Create Chat controller
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/ChatController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/ChatMessage.java
Labels: enhancement, back end

#84 Fix backend bugs
  UniVerseAPI/universe/pom.xml
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/JwtUtil.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/SecurityConfig.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/authentication/config/PasswordEncoder.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/JobOffer.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Notification.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Post.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/User.java
Labels: bug, enhancement, back end

#85 added test plan document
  docs/test-plan.docx
Labels: documentation

#88 Fix backend bugs
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/ChatController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/FriendshipController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/LikeController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/UserController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/ChatDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/MessageDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Chat.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/ChatMessage.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Comment.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Follow.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Friendship.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Group.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/GroupEvent.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/GroupMembership.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/JobOffer.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Like.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Message.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/News.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Notification.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Post.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/User.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/ChatRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/FriendshipRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/LikeRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/MessageRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/UserRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/ChatService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/CommentService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/FriendshipService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/LikeService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/PostService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/UserService.java
  UniVerseAPI/universe/src/main/resources/application.yml
Labels: enhancement, back end

#89 Create backend authentication with cookies
  UniVerseAPI/universe/pom.xml
  UniVerseAPI/universe/src/main/java/com/unidev/universe/config/JwtAuthenticationFilter.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/config/SecurityConfig.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/AuthController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/User.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/requests/LoginRequest.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/requests/RegisterRequest.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/JwtResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/UserFollowerResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/UserFollowingResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/UserJwtResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/UserResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/AuthService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/JwtService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/UserService.java
  UniVerseAPI/universe/src/main/resources/application.yml
Labels: enhancement, back end

#91 Finish and optimise frontend Phase 1
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/api/axios.js
  UniVerseUI/universe-ui/src/api/usersApi.js
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/BottomNav.jsx
  UniVerseUI/universe-ui/src/components/Feed.jsx
  UniVerseUI/universe-ui/src/components/Post.jsx
  UniVerseUI/universe-ui/src/components/Sidebar.jsx
  UniVerseUI/universe-ui/src/components/Topbar.jsx
  UniVerseUI/universe-ui/src/components/fallbacks/RouterErrorFallback.jsx
  UniVerseUI/universe-ui/src/hooks/useLogout.js
  UniVerseUI/universe-ui/src/hooks/useRefreshToken.js
  UniVerseUI/universe-ui/src/layouts/MainLayout.jsx
  UniVerseUI/universe-ui/src/pages/Courses.jsx
  UniVerseUI/universe-ui/src/pages/Events.jsx
  UniVerseUI/universe-ui/src/pages/Groups.jsx
  UniVerseUI/universe-ui/src/pages/JobDetails.jsx
  UniVerseUI/universe-ui/src/pages/Jobs.jsx
  UniVerseUI/universe-ui/src/pages/News.jsx
  UniVerseUI/universe-ui/src/pages/NewsDetails.jsx
  UniVerseUI/universe-ui/src/pages/Profile.jsx
  UniVerseUI/universe-ui/src/routes/PersistLogin.jsx
  UniVerseUI/universe-ui/src/routes/ProtectedRoute.jsx
  UniVerseUI/universe-ui/src/styles/style.css
  UniVerseUI/universe-ui/vite.config.js
Labels: enhancement, front end

#93 Connect frontend to backend
  UniVerseAPI/universe/src/main/java/com/unidev/universe/UniverseApplication.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/config/SecurityConfig.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/AuthController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/CommentController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/JobsController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/LikeController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/NewsController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/PostController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/controllers/UserController.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/dto/CommentDTO.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/Comment.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/News.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/entities/User.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/CommentRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/NewsRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/repository/PostRepository.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/JwtResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/AuthService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/CommentService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/JobService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/LikeService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/NewsService.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/services/PostService.java
  UniVerseUI/universe-ui/src/api/axios.js
  UniVerseUI/universe-ui/src/api/eventsApi.js
  UniVerseUI/universe-ui/src/api/jobsApi.js
  UniVerseUI/universe-ui/src/api/newsApi.js
  UniVerseUI/universe-ui/src/api/postsApi.js
  UniVerseUI/universe-ui/src/api/usersApi.js
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
Labels: enhancement, back end, front end

#94 Organise frontend project structure
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/Comment.jsx
  UniVerseUI/universe-ui/src/components/CommentSection.jsx
  UniVerseUI/universe-ui/src/components/CreatePostForm.jsx
  UniVerseUI/universe-ui/src/components/Feed.jsx
  UniVerseUI/universe-ui/src/components/Post.jsx
  UniVerseUI/universe-ui/src/components/SocialPanel.jsx
  UniVerseUI/universe-ui/src/components/Topbar.jsx
  UniVerseUI/universe-ui/src/layouts/MainLayout.jsx
  UniVerseUI/universe-ui/src/pages/Chat.jsx
  UniVerseUI/universe-ui/src/pages/Chats.jsx
  UniVerseUI/universe-ui/src/pages/Events.jsx
  UniVerseUI/universe-ui/src/pages/Home.jsx
  UniVerseUI/universe-ui/src/pages/JobDetails.jsx
  UniVerseUI/universe-ui/src/pages/Jobs.jsx
  UniVerseUI/universe-ui/src/pages/Landing.jsx
  UniVerseUI/universe-ui/src/pages/News.jsx
  UniVerseUI/universe-ui/src/pages/NewsDetails.jsx
  UniVerseUI/universe-ui/src/pages/Profile.jsx
  UniVerseUI/universe-ui/src/routes/ProtectedRoute.jsx
  UniVerseUI/universe-ui/src/services/chatsService.js
  UniVerseUI/universe-ui/src/services/eventsService.js
  UniVerseUI/universe-ui/src/services/jobsService.js
  UniVerseUI/universe-ui/src/services/newsService.js
  UniVerseUI/universe-ui/src/services/postsService.js
  UniVerseUI/universe-ui/src/services/usersService.js
Labels: enhancement, front end
