Repository Shredrox/UniVerse, pull requests merged in 2023-11, with the labels that each got.

#3 Add the Functional and Architectural design
  docs/architectural-design.pdf
  docs/functional-design.pdf
Labels: documentation

#10 Initial UI Merge
  UniVerseUI/ui.txt
  UniVerseUI/universe-ui/.eslintrc.cjs
  UniVerseUI/universe-ui/.gitignore
  UniVerseUI/universe-ui/README.md
  UniVerseUI/universe-ui/index.html
  UniVerseUI/universe-ui/package-lock.json
  UniVerseUI/universe-ui/package.json
  UniVerseUI/universe-ui/public/vite.svg
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/assets/icons/favicon-universe.ico
  UniVerseUI/universe-ui/src/assets/icons/icon-bell.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-briefcase.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-calendar.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-chat.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-cog.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-comment.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-course.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-courses.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-heart.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-home.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-job.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-newspaper.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-search-outline.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-task.svg
  UniVerseUI/universe-ui/src/assets/icons/icon-users.svg
  UniVerseUI/universe-ui/src/assets/images/logo-universe.png
  UniVerseUI/universe-ui/src/components/Sidebar.jsx
  UniVerseUI/universe-ui/src/components/Topbar.jsx
  UniVerseUI/universe-ui/src/components/UserPanel.jsx
  UniVerseUI/universe-ui/src/layouts/MainLayout.jsx
  UniVerseUI/universe-ui/src/main.jsx
  UniVerseUI/universe-ui/src/pages/Chats.jsx
  UniVerseUI/universe-ui/src/pages/Courses.jsx
  UniVerseUI/universe-ui/src/pages/Events.jsx
  UniVerseUI/universe-ui/src/pages/Groups.jsx
  UniVerseUI/universe-ui/src/pages/Home.jsx
  UniVerseUI/universe-ui/src/pages/Jobs.jsx
  UniVerseUI/universe-ui/src/pages/Landing.jsx
  UniVerseUI/universe-ui/src/pages/News.jsx
  UniVerseUI/universe-ui/src/pages/Settings.jsx
  UniVerseUI/universe-ui/src/styles/style.css
  UniVerseUI/universe-ui/vite.config.js
Labels: enhancement, front end

#13 Create Landing page
  UniVerseUI/universe-ui/index.html
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/assets/images/background-landing-page.jpg
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/UserPanel.jsx
  UniVerseUI/universe-ui/src/layouts/MainLayout.jsx
  UniVerseUI/universe-ui/src/pages/Landing.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#16 Restructure frontend routes and navigation
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/Sidebar.jsx
  UniVerseUI/universe-ui/src/components/UserPanel.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#27 Create Home page
  UniVerseUI/universe-ui/package-lock.json
  UniVerseUI/universe-ui/package.json
  UniVerseUI/universe-ui/src/api/postsApi.js
  UniVerseUI/universe-ui/src/api/usersApi.js
  UniVerseUI/universe-ui/src/components/CreatePostForm.jsx
  UniVerseUI/universe-ui/src/components/Feed.jsx
  UniVerseUI/universe-ui/src/components/Post.jsx
  UniVerseUI/universe-ui/src/main.jsx
  UniVerseUI/universe-ui/src/pages/Home.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end

#38 Create user responses.
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserFollowerResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserFollowingResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserJwtResponse.java
  UniVerseAPI/universe/src/main/java/com/unidev/universe/responses/user/UserResponse.java
Labels: enhancement, back end

#43 Create Profile page
  UniVerseUI/universe-ui/src/App.jsx
  UniVerseUI/universe-ui/src/api/usersApi.js
  UniVerseUI/universe-ui/src/components/AccessForm.jsx
  UniVerseUI/universe-ui/src/components/Post.jsx
  UniVerseUI/universe-ui/src/components/Sidebar.jsx
  UniVerseUI/universe-ui/src/components/UserPanel.jsx
  UniVerseUI/universe-ui/src/layouts/MainLayout.jsx
  UniVerseUI/universe-ui/src/pages/Profile.jsx
  UniVerseUI/universe-ui/src/styles/style.css
Labels: enhancement, front end
